In [1]:
import numpy as np

In [5]:
arr = np.random.rand(32, 32, 3)

In [7]:
arr.shape

(32, 32, 3)

In [10]:
arr.reshape(-1, 32*32*3).shape

(1, 3072)

In [11]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [13]:
c.shape

(2, 3)

In [14]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)

In [15]:
a

array([[ 0.40910731, -0.06516845,  1.05760369],
       [ 0.57190959,  1.04061728,  0.28101109],
       [-0.22247119,  0.56697533, -1.83651116],
       [-0.35468102, -1.48469151, -0.63615963]])

In [16]:
b

array([[-0.98193373, -0.05140879],
       [ 0.72498557, -1.98771412],
       [ 1.35712585, -0.61333565]])

In [18]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [19]:
c.shape

(3, 3)

In [20]:
c

array([[ 1.3274299 , -1.34314139, -0.5676346 ],
       [ 0.61040945,  0.53805789, -0.49584708],
       [ 1.69445834, -2.34989129, -3.64688584]])